language: go
go:
  - 1.7.x
  - tip
install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
before_script:
script:
  - glide install
  - go test $(glide nv)
  - goveralls -service=travis-ci -ignore="bootstrap.go,recorder/elasticsearch/config.go,config/config.go,lib/dummies.go,config/errors.go,reader/expvar/config.go, lib/log.go,datatype/maps_reader_mock.go,reader/config_mock.go"
after_success:
  - bash <(curl -s https://codecov.io/bash)
