language: go
go:
  - 1.7.x
  - tip
install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
before_script:
script:
  - glide install
  - go test $(glide nv)
  - goveralls -service=travis-ci
