sudo: required

language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip

services:
  - docker

install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls

script:
  - glide install
  - ./bin/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
