sudo: required

language: go

go:
  - 1.7.x
  - tip

services:
  - docker

install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls

script:
  - glide install
  - go test $(glide nv)
  - goveralls -service=travis-ci -ignore="bootstrap.go,reader/testing/config_mock.go,reader/testing/testing.go,reader/testing/example_provider.go,reader/testing/testing_token.go,reader/testing/testing_construction.go,reader/testing/testing_endpoints.go,recorder/testing/config_mock.go,recorder/testing/testing.go,recorder/testing/example_provider.go,recorder/testing/testing_token.go,recorder/testing/testing_construction.go,recorder/testing/testing_endpoints.go"
