sudo: required

language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

matrix:
  allow_failures:
    - go: tip

services:
  - docker

install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls

script:
  - glide install
  - go test $(glide nv)

after_success:
  - goveralls -service=travis-ci -ignore="reader/testing/config.go,reader/testing/testing.go,reader/testing/example_provider.go,reader/testing/testing_token.go,reader/testing/testing_construction.go,reader/testing/testing_communication.go,reader/testing/testing_endpoints.go,recorder/testing/config.go,recorder/testing/testing.go,recorder/testing/example_provider.go,recorder/testing/testing_token.go,recorder/testing/testing_construction.go,recorder/testing/testing_communication.go,recorder/testing/testing_endpoints.go,.travis.yml"
