settings:
    log_level: warn

readers:
    my_app:                         # service name
        type: expvar
        endpoint: localhost:1234/debug/vars
        type_name: my_app
        map_file: maps.yml
        interval: 500ms
        timeout: 3s
    my_app2:                        # service name
        type: expvar
        endpoint: localhost:1235/debug/vars
        type_name: my_ap2
        interval: 500ms
        timeout: 13s
    self:                           # expipe's self metric
        type: self                  # only used for this reason
        type_name: expipe
        interval: 500ms

recorders:
    elastic1:                       # service name
        type: elasticsearch
        endpoint: http://127.0.0.1:9200
        index_name: expipe
        timeout: 8s
    elastic2:
        type: elasticsearch
        endpoint: http://127.0.0.1:9200
        index_name: expipe
        timeout: 8s
    elastic3:
        type: elasticsearch
        endpoint: http://127.0.0.1:9200
        index_name: expipe
        timeout: 18s

routes:
    route1:
        readers:
            - my_app
        recorders:
            - elastic1
    route2:
        readers:
            - my_app2
        recorders:
            - elastic2
    self_route:
        readers:
            - self
        recorders:
            - elastic3
